export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_EMAIL_VERIFICATION_SEND_REQUEST = "USER_EMAIL_VERIFICATION_SEND_REQUEST";
export const USER_EMAIL_VERIFICATION_SEND_FAIL = "USER_EMAIL_VERIFICATION_SEND_FAIL";

export const USER_RESET_PASSWORD_SEND_REQUEST = "USER_RESET_PASSWORD_SEND_REQUEST";
export const USER_RESET_PASSWORD_SEND_SUCCESS = "USER_RESET_PASSWORD_SEND_SUCCESS";
export const USER_RESET_PASSWORD_SEND_FAIL = "USER_RESET_PASSWORD_SEND_FAIL";