export const FETCH_DEMANDE_REQUEST = "FETCH_DEMANDE_REQUEST";
export const FETCH_DEMANDE_SUCCESS = "FETCH_DEMANDE_SUCCESS";
export const FETCH_DEMANDE_FAIL = "FETCH_DEMANDE_FAIL";

export const ACCEPT_DEMANDE_REQUEST = "ACCEPT_DEMANDE_REQUEST";
export const ACCEPT_DEMANDE_SUCCESS = "ACCEPT_DEMANDE_SUCCESS";
export const ACCEPT_DEMANDE_FAIL = "ACCEPT_DEMANDE_FAIL";