//user
export const PROFILE_SEEN_REQUEST = "PROFILE_SEEN_REQUEST";
export const PROFILE_SEEN_SUCCESS = "PROFILE_SEEN_SUCCESS";
export const PROFILE_SEEN_FAIL = "PROFILE_SEEN_FAIL";

export const UPDATE_PIC_REQUEST = "UPDATE_PIC_REQUEST";
export const UPDATE_PIC_SUCCESS = "UPDATE_PIC_SUCCESS";
export const UPDATE_PIC_FAIL = "UPDATE_PIC_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

//Stade
export const STADE_SEEN_REQUEST = "STADE_SEEN_REQUEST";
export const STADE_SEEN_SUCCESS = "STADE_SEEN_SUCCESS";
export const STADE_SEEN_FAIL = "STADE_SEEN_FAIL";

export const MY_STADE_SEEN_REQUEST = "MY_STADE_SEEN_REQUEST";
export const MY_STADE_SEEN_SUCCESS = "MY_STADE_SEEN_SUCCESS";
export const MY_STADE_SEEN_FAIL = "MY_STADE_SEEN_FAIL";

export const STADE_ADD_REQUEST = "STADE_ADD_REQUEST";
export const STADE_ADD_SUCCESS = "STADE_ADD_SUCCESS";
export const STADE_ADD_FAIL = "STADE_ADD_FAIL";

export const STADE_DELETE_REQUEST = "STADE_DELETE_REQUEST";
export const STADE_DELETE_SUCCESS = "STADE_DELETE_SUCCESS";
export const STADE_DELETE_FAIL = "STADE_DELETE_FAIL";

//reservation
export const EVENT_ADD_REQUEST = "EVENT_ADD_REQUEST";
export const EVENT_ADD_SUCCESS = "EVENT_ADD_SUCCESS";
export const EVENT_ADD_FAIL = "EVENT_ADD_FAIL";

export const EVENT_SEEN_REQUEST = "EVENT_SEEN_REQUEST";
export const EVENT_SEEN_SUCCESS = "EVENT_SEEN_SUCCESS";
export const EVENT_SEEN_FAIL = "EVENT_SEEN_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

//search
export const PLAYER_SEARCH_REQUEST = "PLAYER_SEARCH_REQUEST";
export const PLAYER_SEARCH_SUCCESS = "PLAYER_SEARCH_SUCCESS";
export const PLAYER_SEARCH_FAIL = "PLAYER_SEARCH_FAIL";

export const USER_FINDBYID_REQUEST = "USER_FINDBYID_REQUEST";
export const USER_FINDBYID_SUCCESS = "USER_FINDBYID_SUCCESS";
export const USER_FINDBYID_FAIL = "USER_FINDBYID_FAIL";

//Ville 
export const VILLE_SEEN_REQUEST = "VILLE_SEEN_REQUEST";
export const VILLE_SEEN_SUCCESS = "VILLE_SEEN_SUCCESS";
export const VILLE_SEEN_FAIL = "VILLE_SEEN_FAIL";