export const SEARCH_STADE_REQUEST = "SEARCH_STADE_REQUEST";
export const SEARCH_STADE_SUCCESS = "SEARCH_STADE_SUCCESS";
export const SEARCH_STADE_FAIL = "SEARCH_STADE_FAIL";

export const GET_STADE_REQUEST = "GET_STADE_REQUEST";
export const GET_STADE_SUCCESS = "GET_STADE_SUCCESS";
export const GET_STADE_FAIL = "GET_STADE_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const RESERVER_ADD_REQUEST = "RESERVER_ADD_REQUEST";
export const RESERVER_ADD_SUCCESS = "RESERVER_ADD_SUCCESS";
export const RESERVER_ADD_FAIL = "RESERVER_ADD_FAIL";

export const RESERVER_CANCEL_REQUEST = "RESERVER_CANCEL_REQUEST";
export const RESERVER_CANCEL_SUCCESS = "RESERVER_CANCEL_SUCCESS";
export const RESERVER_CANCEL_FAIL = "RESERVER_CANCEL_FAIL";

export const SEARCH_GROUP_REQUEST = "SEARCH_GROUP_REQUEST";
export const SEARCH_GROUP_SUCCESS = "SEARCH_GROUP_SUCCESS";
export const SEARCH_GROUP_FAIL = "SEARCH_GROUP_FAIL";

export const ACCEPTER_GROUP_REQUEST = "ACCEPTER_GROUP_REQUEST";
export const ACCEPTER_GROUP_SUCCESS = "ACCEPTER_GROUP_SUCCESS";
export const ACCEPTER_GROUP_FAIL = "ACCEPTER_GROUP_FAIL";

export const REJETER_GROUP_REQUEST = "REJETER_GROUP_REQUEST";
export const REJETER_GROUP_SUCCESS = "REJETER_GROUP_SUCCESS";
export const REJETER_GROUP_FAIL = "REJETER_GROUP_FAIL";

export const DEMANDE_GROUP_REQUEST = "DEMANDE_GROUP_REQUEST";
export const DEMANDE_GROUP_SUCCESS = "DEMANDE_GROUP_SUCCESS";
export const DEMANDE_GROUP_FAIL = "DEMANDE_GROUP_FAIL";